### ISSUE TITLE
Image cropping in news items

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/vassallandcoldharbour#20]
Live site.

We need to have the ability for news items to be able to determine what bit of the picture gets used by the front page carousel. Rather too many people are getting their heads cut off.

![image](https://cloud.githubusercontent.com/assets/6060985/7723579/c1ece4f0-fee1-11e4-8837-d377e2d0ed95.png)

**Comment by djwesto** [comment]
@pmackay I'm not sure how this might work. I think @GilesGibson is asking about the idea of providing a better cropping tool – worth reflecting on since we were discussing this the other day.

As to the way this now works, we've fixed the problems we were seeing earlier and now just need to improve the way the front page carousel looks, which I've started to do with my latest commit:

![screenshot 2015-05-27 16 21 21 2](https://cloud.githubusercontent.com/assets/702685/7839835/77fbcc0c-048c-11e5-9145-67a7f97e3b83.png)

Please check on live, @GilesGibson?

**Comment by pmackay** [comment]
Fixed. Might need to think which other images need cropping.
